/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccesoRouteImport } from './routes/acceso'
import { Route as AdministracionRouteRouteImport } from './routes/administracion/route'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as AdministracionIndexRouteImport } from './routes/administracion/index'
import { Route as AdministracionCatalogoRouteImport } from './routes/administracion/catalogo'
import { Route as AdministracionParametrosRouteImport } from './routes/administracion/parametros'
import { Route as AdministracionSeriesRouteImport } from './routes/administracion/series'
import { Route as AdministracionUsuariosRouteImport } from './routes/administracion/usuarios'
import { Route as ComprobantesIndexRouteImport } from './routes/comprobantes/index'
import { Route as ComprobantesComprobanteIdRouteImport } from './routes/comprobantes/$comprobanteId'
import { Route as CotizacionesIndexRouteImport } from './routes/cotizaciones/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoRoute = AccesoRouteImport.update({
  id: '/acceso',
  path: '/acceso',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracionRouteRoute = AdministracionRouteRouteImport.update({
  id: '/administracion',
  path: '/administracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracionIndexRoute = AdministracionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdministracionRouteRoute,
} as any)
const AdministracionCatalogoRoute = AdministracionCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AdministracionRouteRoute,
} as any)
const AdministracionParametrosRoute =
  AdministracionParametrosRouteImport.update({
    id: '/parametros',
    path: '/parametros',
    getParentRoute: () => AdministracionRouteRoute,
  } as any)
const AdministracionSeriesRoute = AdministracionSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => AdministracionRouteRoute,
} as any)
const AdministracionUsuariosRoute = AdministracionUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdministracionRouteRoute,
} as any)
const ComprobantesIndexRoute = ComprobantesIndexRouteImport.update({
  id: '/comprobantes/',
  path: '/comprobantes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprobantesComprobanteIdRoute =
  ComprobantesComprobanteIdRouteImport.update({
    id: '/comprobantes/$comprobanteId',
    path: '/comprobantes/$comprobanteId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CotizacionesIndexRoute = CotizacionesIndexRouteImport.update({
  id: '/cotizaciones/',
  path: '/cotizaciones/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administracion': typeof AdministracionRouteRouteWithChildren
  '/acceso': typeof AccesoRoute
  '/configuracion': typeof ConfiguracionRoute
  '/administracion/catalogo': typeof AdministracionCatalogoRoute
  '/administracion/parametros': typeof AdministracionParametrosRoute
  '/administracion/series': typeof AdministracionSeriesRoute
  '/administracion/usuarios': typeof AdministracionUsuariosRoute
  '/comprobantes/$comprobanteId': typeof ComprobantesComprobanteIdRoute
  '/administracion/': typeof AdministracionIndexRoute
  '/comprobantes/': typeof ComprobantesIndexRoute
  '/cotizaciones/': typeof CotizacionesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/configuracion': typeof ConfiguracionRoute
  '/administracion/catalogo': typeof AdministracionCatalogoRoute
  '/administracion/parametros': typeof AdministracionParametrosRoute
  '/administracion/series': typeof AdministracionSeriesRoute
  '/administracion/usuarios': typeof AdministracionUsuariosRoute
  '/comprobantes/$comprobanteId': typeof ComprobantesComprobanteIdRoute
  '/administracion': typeof AdministracionIndexRoute
  '/comprobantes': typeof ComprobantesIndexRoute
  '/cotizaciones': typeof CotizacionesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administracion': typeof AdministracionRouteRouteWithChildren
  '/acceso': typeof AccesoRoute
  '/configuracion': typeof ConfiguracionRoute
  '/administracion/catalogo': typeof AdministracionCatalogoRoute
  '/administracion/parametros': typeof AdministracionParametrosRoute
  '/administracion/series': typeof AdministracionSeriesRoute
  '/administracion/usuarios': typeof AdministracionUsuariosRoute
  '/comprobantes/$comprobanteId': typeof ComprobantesComprobanteIdRoute
  '/administracion/': typeof AdministracionIndexRoute
  '/comprobantes/': typeof ComprobantesIndexRoute
  '/cotizaciones/': typeof CotizacionesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administracion'
    | '/acceso'
    | '/configuracion'
    | '/administracion/catalogo'
    | '/administracion/parametros'
    | '/administracion/series'
    | '/administracion/usuarios'
    | '/comprobantes/$comprobanteId'
    | '/administracion/'
    | '/comprobantes/'
    | '/cotizaciones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceso'
    | '/configuracion'
    | '/administracion/catalogo'
    | '/administracion/parametros'
    | '/administracion/series'
    | '/administracion/usuarios'
    | '/comprobantes/$comprobanteId'
    | '/administracion'
    | '/comprobantes'
    | '/cotizaciones'
  id:
    | '__root__'
    | '/'
    | '/administracion'
    | '/acceso'
    | '/configuracion'
    | '/administracion/catalogo'
    | '/administracion/parametros'
    | '/administracion/series'
    | '/administracion/usuarios'
    | '/comprobantes/$comprobanteId'
    | '/administracion/'
    | '/comprobantes/'
    | '/cotizaciones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministracionRouteRoute: typeof AdministracionRouteRouteWithChildren
  AccesoRoute: typeof AccesoRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  ComprobantesComprobanteIdRoute: typeof ComprobantesComprobanteIdRoute
  ComprobantesIndexRoute: typeof ComprobantesIndexRoute
  CotizacionesIndexRoute: typeof CotizacionesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso': {
      id: '/acceso'
      path: '/acceso'
      fullPath: '/acceso'
      preLoaderRoute: typeof AccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracion': {
      id: '/administracion'
      path: '/administracion'
      fullPath: '/administracion'
      preLoaderRoute: typeof AdministracionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracion/': {
      id: '/administracion/'
      path: '/'
      fullPath: '/administracion/'
      preLoaderRoute: typeof AdministracionIndexRouteImport
      parentRoute: typeof AdministracionRouteRoute
    }
    '/administracion/catalogo': {
      id: '/administracion/catalogo'
      path: '/catalogo'
      fullPath: '/administracion/catalogo'
      preLoaderRoute: typeof AdministracionCatalogoRouteImport
      parentRoute: typeof AdministracionRouteRoute
    }
    '/administracion/parametros': {
      id: '/administracion/parametros'
      path: '/parametros'
      fullPath: '/administracion/parametros'
      preLoaderRoute: typeof AdministracionParametrosRouteImport
      parentRoute: typeof AdministracionRouteRoute
    }
    '/administracion/series': {
      id: '/administracion/series'
      path: '/series'
      fullPath: '/administracion/series'
      preLoaderRoute: typeof AdministracionSeriesRouteImport
      parentRoute: typeof AdministracionRouteRoute
    }
    '/administracion/usuarios': {
      id: '/administracion/usuarios'
      path: '/usuarios'
      fullPath: '/administracion/usuarios'
      preLoaderRoute: typeof AdministracionUsuariosRouteImport
      parentRoute: typeof AdministracionRouteRoute
    }
    '/comprobantes/': {
      id: '/comprobantes/'
      path: '/comprobantes'
      fullPath: '/comprobantes/'
      preLoaderRoute: typeof ComprobantesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprobantes/$comprobanteId': {
      id: '/comprobantes/$comprobanteId'
      path: '/comprobantes/$comprobanteId'
      fullPath: '/comprobantes/$comprobanteId'
      preLoaderRoute: typeof ComprobantesComprobanteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizaciones/': {
      id: '/cotizaciones/'
      path: '/cotizaciones'
      fullPath: '/cotizaciones/'
      preLoaderRoute: typeof CotizacionesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdministracionRouteRouteChildren {
  AdministracionCatalogoRoute: typeof AdministracionCatalogoRoute
  AdministracionParametrosRoute: typeof AdministracionParametrosRoute
  AdministracionSeriesRoute: typeof AdministracionSeriesRoute
  AdministracionUsuariosRoute: typeof AdministracionUsuariosRoute
  AdministracionIndexRoute: typeof AdministracionIndexRoute
}

const AdministracionRouteRouteChildren: AdministracionRouteRouteChildren = {
  AdministracionCatalogoRoute: AdministracionCatalogoRoute,
  AdministracionParametrosRoute: AdministracionParametrosRoute,
  AdministracionSeriesRoute: AdministracionSeriesRoute,
  AdministracionUsuariosRoute: AdministracionUsuariosRoute,
  AdministracionIndexRoute: AdministracionIndexRoute,
}

const AdministracionRouteRouteWithChildren =
  AdministracionRouteRoute._addFileChildren(AdministracionRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministracionRouteRoute: AdministracionRouteRouteWithChildren,
  AccesoRoute: AccesoRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  ComprobantesComprobanteIdRoute: ComprobantesComprobanteIdRoute,
  ComprobantesIndexRoute: ComprobantesIndexRoute,
  CotizacionesIndexRoute: CotizacionesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
