/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as AdministracionIndexRouteImport } from './routes/administracion/index'
import { Route as AdministracionCatalogoRouteImport } from './routes/administracion/catalogo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracionIndexRoute = AdministracionIndexRouteImport.update({
  id: '/administracion/',
  path: '/administracion/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracionCatalogoRoute = AdministracionCatalogoRouteImport.update({
  id: '/administracion/catalogo',
  path: '/administracion/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/administracion/catalogo': typeof AdministracionCatalogoRoute
  '/administracion/': typeof AdministracionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/administracion/catalogo': typeof AdministracionCatalogoRoute
  '/administracion': typeof AdministracionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/administracion/catalogo': typeof AdministracionCatalogoRoute
  '/administracion/': typeof AdministracionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/configuracion' | '/administracion/catalogo' | '/administracion/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/configuracion' | '/administracion/catalogo' | '/administracion'
  id:
    | '__root__'
    | '/'
    | '/configuracion'
    | '/administracion/catalogo'
    | '/administracion/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  AdministracionCatalogoRoute: typeof AdministracionCatalogoRoute
  AdministracionIndexRoute: typeof AdministracionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracion/': {
      id: '/administracion/'
      path: '/administracion'
      fullPath: '/administracion/'
      preLoaderRoute: typeof AdministracionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracion/catalogo': {
      id: '/administracion/catalogo'
      path: '/administracion/catalogo'
      fullPath: '/administracion/catalogo'
      preLoaderRoute: typeof AdministracionCatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  AdministracionCatalogoRoute: AdministracionCatalogoRoute,
  AdministracionIndexRoute: AdministracionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
